### PR TITLE
takehome xex's and a mystery xex

### PR DESCRIPTION
**Pull request by glitchgod0**

### CODE REVIEW

**Comment by ihatecompvir** [comment]
For a bit of background on the mystery xex here, it is the E3 2010 build of DC1. I believe it originates from a kit used to demonstrate Kinect games at E3 2010, I saw a very similar kit (which also had this build on it) on eBay a while ago

**Comment by jfoshee900lbs** [comment]
👀

**Comment by jnackmclain** [comment]
👀👀👀

**Comment by glitchgod0** [comment]
> For a bit of background on the mystery xex here, it is the E3 2010 build of DC1. I believe it originates from a kit used to demonstrate Kinect games at E3 2010, I saw a very similar kit (which also had this build on it) on eBay a while ago

Do you still have (or know where to get) the files for that build?

**Pull request merged**
